#!/usr/bin/env bun

/**
 * Prepare step for the GitLab CI/CD Component (Pass 1 of the two-pass
 * review flow).
 *
 * Responsibilities:
 *   1. Parse GitLab CI env into a normalized context.
 *   2. Decide whether this pipeline should run a review (automaticReview
 *      flag + merge_request_event source).
 *   3. Ensure a sticky tracking note exists on the MR; reuse the existing
 *      one if a prior pipeline already created it.
 *   4. Fetch + persist the three review artifacts (mr.diff,
 *      existing_comments.json, mr_description.txt).
 *   5. Resolve review depth presets into concrete model+effort.
 *   6. Generate the Pass-1 (candidate-generation) prompt and write it
 *      to the shared prompt file.
 *   7. Write a JSON state file consumed by `gitlab-prepare-validator`
 *      (Pass 2) and `gitlab-update-comment-link` (post-step).
 *
 * Pass 2 is generated later by `gitlab-prepare-validator.ts`, which
 * reads this state file and overwrites the prompt file with the
 * Pass-2 content before the second `droid exec` invocation.
 */

import * as fs from "fs/promises";
import * as path from "path";
import { parseGitlabContext, isMergeRequestContext } from "../gitlab/context";
import {
  setupGitlabToken,
  MissingGitlabTokenError,
  UnexpandedGitlabTokenError,
} from "../gitlab/token";
import { GitlabClient } from "../gitlab/api/client";
import {
  buildTrackingNoteBody,
  findExistingTrackingNote,
} from "../gitlab/operations/tracking-note";
import { computeReviewArtifacts } from "../gitlab/data/review-artifacts";
import { generateGitlabReviewCandidatesPrompt } from "../gitlab/prompts/candidates";
import type { GitlabReviewPromptContext } from "../gitlab/prompts/types";
import { resolveReviewConfig } from "../utils/review-depth";
import { applyModelPolicyFallback } from "../utils/model-policy";
import {
  buildReviewSessionTag,
  type ReviewPass,
} from "../utils/review-session-tag";
import { setupDroidSettings } from "../../base-action/src/setup-droid-settings";

export type PrepareState = {
  shouldRunReview: boolean;
  projectId: string;
  projectPath: string;
  mrIid: number | null;
  trackingNoteId: number | null;
  diffBaseSha: string | null;
  sourceBranchSha: string | null;
  pipelineUrl: string | null;
  jobUrl: string | null;
  promptPath: string | null;
  resolvedModel: string | null;
  resolvedReasoningEffort: string | null;

  diffPath: string | null;
  commentsPath: string | null;
  descriptionPath: string | null;
  candidatesPath: string | null;
  validatedPath: string | null;

  mrTitle: string | null;
  sourceBranch: string | null;
  targetBranch: string | null;
  headSha: string | null;
  includeSuggestions: boolean;
  securityReviewEnabled: boolean;

  reason?: string;
  /**
   * Set by gitlab-prepare-validator when Pass 1 left no usable candidates
   * file, so Pass 2 never runs for real and never writes the validated
   * review. The posting step reads it to no-op instead of failing the job.
   */
  validatorSkippedReason?: string;
};

// The Component runs each step as its own process, so these paths have to
// resolve identically in all of them; the other entrypoints import them
// from here rather than redefining them.
function promptFilePath(): string {
  return process.env.DROID_PROMPT_FILE || "/tmp/droid-prompts/droid-prompt.txt";
}

export function promptsDir(): string {
  return path.dirname(promptFilePath());
}

function candidatesFilePath(): string {
  return (
    process.env.REVIEW_CANDIDATES_PATH ||
    path.join(promptsDir(), "review_candidates.json")
  );
}

export function validatedFilePath(): string {
  return (
    process.env.REVIEW_VALIDATED_PATH ||
    path.join(promptsDir(), "review_validated.json")
  );
}

function resolvedEnvShimPath(): string {
  return (
    process.env.DROID_RESOLVED_ENV_FILE ||
    path.join(promptsDir(), "resolved-env.sh")
  );
}

/**
 * Deliberately not under `CI_PROJECT_DIR`: that holds the checked-out MR, so
 * a branch could commit `.droid-state.json` as a symlink and redirect this
 * write anywhere the job can reach.
 */
export function stateFilePath(): string {
  return (
    process.env.DROID_STATE_FILE || path.join(promptsDir(), ".droid-state.json")
  );
}

function shellEscape(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

async function writeResolvedEnvShim(
  model: string | null,
  reasoningEffort: string | null,
  extras: Record<string, string | null>,
): Promise<void> {
  const filePath = resolvedEnvShimPath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const lines = [
    "# Generated by gitlab-prepare; source this to expose resolved review presets.",
    `export RESOLVED_MODEL=${shellEscape(model ?? "")}`,
    `export RESOLVED_REASONING_EFFORT=${shellEscape(reasoningEffort ?? "")}`,
  ];
  for (const [k, v] of Object.entries(extras)) {
    lines.push(`export ${k}=${shellEscape(v ?? "")}`);
  }
  await fs.writeFile(filePath, lines.join("\n") + "\n");
  console.log(`Wrote resolved env shim to ${filePath}`);
}

async function writeState(state: PrepareState): Promise<void> {
  const filePath = stateFilePath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(state, null, 2));
  console.log(`Wrote droid state to ${filePath}`);
}

async function run(): Promise<void> {
  const context = parseGitlabContext();

  const baseState: PrepareState = {
    shouldRunReview: false,
    projectId: context.project.id,
    projectPath: context.project.pathWithNamespace,
    mrIid: context.mr?.iid ?? null,
    trackingNoteId: null,
    diffBaseSha: context.mr?.diffBaseSha ?? null,
    sourceBranchSha: context.mr?.sourceBranchSha ?? null,
    pipelineUrl: context.pipelineUrl,
    jobUrl: context.jobUrl,
    promptPath: null,
    resolvedModel: null,
    resolvedReasoningEffort: null,
    diffPath: null,
    commentsPath: null,
    descriptionPath: null,
    candidatesPath: null,
    validatedPath: null,
    mrTitle: context.mr?.title ?? null,
    sourceBranch: null,
    targetBranch: null,
    headSha: null,
    includeSuggestions: true,
    securityReviewEnabled: false,
  };

  if (!isMergeRequestContext(context)) {
    console.log(
      "Not a merge_request_event pipeline; skipping droid review prepare.",
    );
    await writeState({
      ...baseState,
      reason: "not-merge-request-event",
    });
    return;
  }

  if (!context.inputs.automaticReview) {
    console.log("automatic_review is disabled; skipping droid review prepare.");
    await writeState({
      ...baseState,
      reason: "automatic-review-disabled",
    });
    return;
  }

  let token: string;
  try {
    token = setupGitlabToken();
  } catch (err) {
    // Both token errors carry setup instructions that are worth surfacing on
    // their own line, ahead of the stack trace.
    if (
      err instanceof MissingGitlabTokenError ||
      err instanceof UnexpandedGitlabTokenError
    ) {
      console.error(err.message);
    }
    throw err;
  }

  // Write ~/.factory/droid/settings.json. Accepts either a raw JSON string
  // or a path to a JSON file (matching the GitHub action's `settings`
  // input). Always sets enableAllProjectMcpServers=true so project-scope
  // MCP servers (if any) are trusted without prompting.
  try {
    await setupDroidSettings(context.inputs.settings || undefined);
  } catch (err) {
    console.warn(
      "Failed to setup droid settings; continuing with defaults:",
      err,
    );
  }

  const client = new GitlabClient(token, context.apiUrl);
  const mrIid = context.mr.iid;
  const projectId = context.project.id;

  const existingNotes = await client.listNotes(projectId, mrIid);
  const existing = findExistingTrackingNote(existingNotes);

  const includeSuggestions =
    (process.env.INCLUDE_SUGGESTIONS ?? "true").toLowerCase() !== "false";
  const securityReviewEnabled = context.inputs.automaticSecurityReview;

  const noteBody = buildTrackingNoteBody({
    state: "running",
    pipelineUrl: context.pipelineUrl,
    jobUrl: context.jobUrl,
    triggerUsername: context.user.login,
    securityReviewRan: securityReviewEnabled,
  });

  let trackingNoteId: number;
  if (existing) {
    await client.updateNote(projectId, mrIid, existing.id, noteBody);
    trackingNoteId = existing.id;
    console.log(`Reused existing tracking note ${trackingNoteId}`);
  } else {
    const created = await client.createNote(projectId, mrIid, noteBody);
    trackingNoteId = created.id;
    console.log(`Created tracking note ${trackingNoteId}`);
  }

  console.log("Computing review artifacts (diff, notes, description)...");
  const artifacts = await computeReviewArtifacts({
    client,
    projectId,
    mrIid,
    outDir: promptsDir(),
  });
  console.log(
    `Artifacts written:\n  ${artifacts.diffPath}\n  ${artifacts.commentsPath}\n  ${artifacts.descriptionPath}`,
  );

  const resolved = await applyModelPolicyFallback(
    resolveReviewConfig({
      reviewModel: context.inputs.reviewModel,
      reasoningEffort: context.inputs.reasoningEffort,
      reviewDepth: context.inputs.reviewDepth,
    }),
    { flowLabel: "code review", modelInputName: "review_model" },
  );
  console.log(
    `Resolved review config: depth=${context.inputs.reviewDepth} ` +
      `explicitModel=${context.inputs.reviewModel || "(empty)"} ` +
      `explicitEffort=${context.inputs.reasoningEffort || "(empty)"} ` +
      `=> model=${resolved.model ?? "(org default)"} effort=${resolved.reasoningEffort ?? "(none)"}`,
  );
  if (resolved.fallbackNote) {
    console.warn(resolved.fallbackNote);
  }

  // The template passes these to `droid exec --tag` verbatim; the shim's
  // single quotes are stripped when it is sourced, so the value is raw JSON.
  // Both passes run inside this one job, so the job id is the run id.
  // GitLab has no separate security pipeline: `automatic_security_review`
  // folds security findings into these same two passes, so the review type
  // is always "code" here (unlike GitHub, which runs a distinct pass).
  const sessionTagJson = (pass: ReviewPass): string =>
    JSON.stringify(
      buildReviewSessionTag({
        pass,
        reviewType: "code",
        platform: "gitlab",
        repo: context.project.pathWithNamespace,
        pr: mrIid,
        runId: context.jobId,
      }),
    );

  await writeResolvedEnvShim(
    resolved.model ?? null,
    resolved.reasoningEffort ?? null,
    {
      DROID_MR_IID: String(mrIid),
      DROID_TRACKING_NOTE_ID: String(trackingNoteId),
      DROID_SESSION_TAG_CANDIDATES: sessionTagJson("candidates"),
      DROID_SESSION_TAG_VALIDATOR: sessionTagJson("validator"),
    },
  );

  const candidatesPath = candidatesFilePath();
  const validatedPath = validatedFilePath();

  const promptCtx: GitlabReviewPromptContext = {
    projectPath: context.project.pathWithNamespace,
    mrIid,
    mrTitle: artifacts.mr.title ?? context.mr.title ?? "",
    sourceBranch: artifacts.mr.source_branch ?? "",
    targetBranch: artifacts.mr.target_branch ?? "",
    headSha:
      artifacts.mr.diff_refs?.head_sha ?? context.mr.sourceBranchSha ?? "",
    diffPath: artifacts.diffPath,
    commentsPath: artifacts.commentsPath,
    descriptionPath: artifacts.descriptionPath,
    candidatesPath,
    validatedPath,
    includeSuggestions,
    securityReviewEnabled,
  };

  const prompt = generateGitlabReviewCandidatesPrompt(promptCtx);
  const promptPath = promptFilePath();
  await fs.mkdir(path.dirname(promptPath), { recursive: true });
  await fs.writeFile(promptPath, prompt);
  console.log(
    `Wrote Pass-1 candidates prompt (${prompt.length} bytes) to ${promptPath}`,
  );

  await writeState({
    ...baseState,
    shouldRunReview: true,
    trackingNoteId,
    promptPath,
    resolvedModel: resolved.model ?? null,
    resolvedReasoningEffort: resolved.reasoningEffort ?? null,
    diffPath: artifacts.diffPath,
    commentsPath: artifacts.commentsPath,
    descriptionPath: artifacts.descriptionPath,
    candidatesPath,
    validatedPath,
    mrTitle: promptCtx.mrTitle,
    sourceBranch: promptCtx.sourceBranch,
    targetBranch: promptCtx.targetBranch,
    headSha: promptCtx.headSha,
    includeSuggestions,
    securityReviewEnabled,
  });
}

if (import.meta.main) {
  run().catch((error) => {
    console.error("gitlab-prepare failed:", error);
    process.exit(1);
  });
}

export { run };
